apiVersion: v1
kind: Service
metadata:
  name: sep-promoters-api
  labels:
    run: sep-promoters-api
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    run: sep-promoters-api