apiVersion: v1
kind: Service
metadata:
  name: sep-promoters-api
  labels:
    app: sep-promoters-api
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: sep-promoters-api