language: node_js
node_js: 
  - 12.18

git:
  clone: true

services: 
  - docker

install: 
  - echo "Nothing needs to be installed"

before_script:
  - echo "Do nothing before script"

script:
  - docker --version
  # Builidng Promoters Api
  - docker build -t sep_promoters-api api/promoters-api
  - docker tag sep_promoters-api mcharaf/sep_promoters-api:latest

  # Building Events Api
  - docker build -t sep_events-api api/events-api
  - docker tag sep_events-api mcharaf/sep_events-api:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mcharaf/sep_promoters-api:latest
  - docker push mcharaf/sep_events-api:latest